import { Lead, Task, Activity, Appointment } from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "James Hartwell",
    phone: "(555) 234-1001",
    email: "james.hartwell@email.com",
    source: "Google Ads",
    status: "new",
    value: 4800,
    createdAt: "2024-07-01",
    tags: ["Hot Lead"],
  },
  {
    id: "2",
    name: "Sofia Reyes",
    phone: "(555) 234-1002",
    email: "sofia.reyes@email.com",
    source: "Referral",
    status: "new",
    value: 7200,
    createdAt: "2024-07-02",
    tags: ["Referral"],
  },
  {
    id: "3",
    name: "Marcus Webb",
    phone: "(555) 234-1003",
    email: "marcus.webb@email.com",
    source: "Facebook",
    status: "contacted",
    value: 3500,
    createdAt: "2024-06-28",
    tags: [],
  },
  {
    id: "4",
    name: "Priya Nair",
    phone: "(555) 234-1004",
    email: "priya.nair@email.com",
    source: "Website",
    status: "contacted",
    value: 5900,
    createdAt: "2024-06-25",
    tags: ["Follow-up"],
  },
  {
    id: "5",
    name: "Tyler Brooks",
    phone: "(555) 234-1005",
    email: "tyler.brooks@email.com",
    source: "Google Ads",
    status: "contacted",
    value: 6100,
    createdAt: "2024-06-22",
    tags: [],
  },
  {
    id: "6",
    name: "Angela Torres",
    phone: "(555) 234-1006",
    email: "angela.torres@email.com",
    source: "Referral",
    status: "appointment_set",
    value: 8400,
    createdAt: "2024-06-18",
    tags: ["Priority"],
  },
  {
    id: "7",
    name: "Derek Owens",
    phone: "(555) 234-1007",
    email: "derek.owens@email.com",
    source: "Yelp",
    status: "appointment_set",
    value: 2900,
    createdAt: "2024-06-15",
    tags: [],
  },
  {
    id: "8",
    name: "Nina Patel",
    phone: "(555) 234-1008",
    email: "nina.patel@email.com",
    source: "Website",
    status: "estimate_sent",
    value: 11200,
    createdAt: "2024-06-10",
    tags: ["High Value"],
  },
  {
    id: "9",
    name: "Chris Langley",
    phone: "(555) 234-1009",
    email: "chris.langley@email.com",
    source: "Google Ads",
    status: "estimate_sent",
    value: 4400,
    createdAt: "2024-06-08",
    tags: [],
  },
  {
    id: "10",
    name: "Rachel Kim",
    phone: "(555) 234-1010",
    email: "rachel.kim@email.com",
    source: "Referral",
    status: "closed_won",
    value: 9600,
    createdAt: "2024-05-30",
    tags: ["Won"],
  },
  {
    id: "11",
    name: "Samuel Ford",
    phone: "(555) 234-1011",
    email: "samuel.ford@email.com",
    source: "Facebook",
    status: "closed_won",
    value: 6800,
    createdAt: "2024-05-25",
    tags: ["Won"],
  },
  {
    id: "12",
    name: "Olivia Grant",
    phone: "(555) 234-1012",
    email: "olivia.grant@email.com",
    source: "Website",
    status: "lost",
    value: 3200,
    createdAt: "2024-05-20",
    tags: ["Lost"],
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Follow up with Angela Torres",
    description: "Call to confirm appointment details",
    dueDate: "2024-07-10",
    status: "pending",
    priority: "high",
    leadId: "6",
    leadName: "Angela Torres",
  },
  {
    id: "t2",
    title: "Send revised estimate to Nina Patel",
    description: "Include discount for bundled services",
    dueDate: "2024-07-09",
    status: "pending",
    priority: "high",
    leadId: "8",
    leadName: "Nina Patel",
  },
  {
    id: "t3",
    title: "Review new leads from Google Ads",
    description: "Qualify and assign to pipeline stages",
    dueDate: "2024-07-08",
    status: "completed",
    priority: "medium",
    leadId: null,
    leadName: null,
  },
  {
    id: "t4",
    title: "Update CRM contact info for Marcus Webb",
    description: "New phone number received via email",
    dueDate: "2024-07-08",
    status: "pending",
    priority: "low",
    leadId: "3",
    leadName: "Marcus Webb",
  },
  {
    id: "t5",
    title: "Prepare weekly pipeline report",
    description: "Summary for Monday morning meeting",
    dueDate: "2024-07-07",
    status: "completed",
    priority: "medium",
    leadId: null,
    leadName: null,
  },
  {
    id: "t6",
    title: "Call Derek Owens about appointment",
    description: "Confirm service type and address",
    dueDate: "2024-07-11",
    status: "pending",
    priority: "medium",
    leadId: "7",
    leadName: "Derek Owens",
  },
  {
    id: "t7",
    title: "Send onboarding docs to Rachel Kim",
    description: "Welcome packet + first invoice",
    dueDate: "2024-07-06",
    status: "completed",
    priority: "high",
    leadId: "10",
    leadName: "Rachel Kim",
  },
  {
    id: "t8",
    title: "Facebook ad creative review",
    description: "Approve next month's creatives",
    dueDate: "2024-07-12",
    status: "pending",
    priority: "low",
    leadId: null,
    leadName: null,
  },
];

export const mockActivities: Activity[] = [
  {
    id: "a1",
    type: "call",
    leadName: "Angela Torres",
    leadId: "6",
    description: "Introductory call — discussed service needs",
    status: "completed",
    date: "2024-07-05",
    duration: "12 min",
  },
  {
    id: "a2",
    type: "email",
    leadName: "Nina Patel",
    leadId: "8",
    description: "Sent initial estimate and brochure",
    status: "completed",
    date: "2024-07-05",
    duration: null,
  },
  {
    id: "a3",
    type: "follow_up",
    leadName: "Chris Langley",
    leadId: "9",
    description: "Follow-up on estimate — no response yet",
    status: "pending",
    date: "2024-07-04",
    duration: null,
  },
  {
    id: "a4",
    type: "call",
    leadName: "Marcus Webb",
    leadId: "3",
    description: "Left voicemail — second attempt",
    status: "no_answer",
    date: "2024-07-04",
    duration: "0 min",
  },
  {
    id: "a5",
    type: "email",
    leadName: "James Hartwell",
    leadId: "1",
    description: "Welcome email sent after form submission",
    status: "completed",
    date: "2024-07-03",
    duration: null,
  },
  {
    id: "a6",
    type: "call",
    leadName: "Sofia Reyes",
    leadId: "2",
    description: "Discovery call — high interest, budget confirmed",
    status: "completed",
    date: "2024-07-03",
    duration: "24 min",
  },
  {
    id: "a7",
    type: "follow_up",
    leadName: "Tyler Brooks",
    leadId: "5",
    description: "SMS follow-up sent via automation",
    status: "completed",
    date: "2024-07-02",
    duration: null,
  },
  {
    id: "a8",
    type: "email",
    leadName: "Derek Owens",
    leadId: "7",
    description: "Appointment confirmation sent",
    status: "completed",
    date: "2024-07-01",
    duration: null,
  },
  {
    id: "a9",
    type: "call",
    leadName: "Priya Nair",
    leadId: "4",
    description: "Discussed pricing — requested written quote",
    status: "completed",
    date: "2024-06-30",
    duration: "18 min",
  },
  {
    id: "a10",
    type: "follow_up",
    leadName: "Olivia Grant",
    leadId: "12",
    description: "Final follow-up — lead went silent",
    status: "completed",
    date: "2024-06-28",
    duration: null,
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "ap1",
    leadName: "Angela Torres",
    leadId: "6",
    service: "Roof Inspection",
    date: "2024-07-08",
    startTime: "09:00",
    endTime: "10:00",
    address: "1842 Elm St, Austin TX",
    status: "confirmed",
  },
  {
    id: "ap2",
    leadName: "Derek Owens",
    leadId: "7",
    service: "Free Estimate",
    date: "2024-07-08",
    startTime: "13:00",
    endTime: "14:00",
    address: "3310 Oak Ave, Austin TX",
    status: "confirmed",
  },
  {
    id: "ap3",
    leadName: "Priya Nair",
    leadId: "4",
    service: "Consultation",
    date: "2024-07-09",
    startTime: "10:00",
    endTime: "11:00",
    address: "908 Maple Dr, Austin TX",
    status: "pending",
  },
  {
    id: "ap4",
    leadName: "Samuel Ford",
    leadId: "11",
    service: "Installation",
    date: "2024-07-10",
    startTime: "08:00",
    endTime: "12:00",
    address: "555 Cedar Ln, Austin TX",
    status: "confirmed",
  },
  {
    id: "ap5",
    leadName: "James Hartwell",
    leadId: "1",
    service: "Free Estimate",
    date: "2024-07-11",
    startTime: "14:00",
    endTime: "15:00",
    address: "217 Pine Ct, Austin TX",
    status: "pending",
  },
  {
    id: "ap6",
    leadName: "Sofia Reyes",
    leadId: "2",
    service: "Consultation",
    date: "2024-07-12",
    startTime: "11:00",
    endTime: "12:00",
    address: "730 Willow Blvd, Austin TX",
    status: "confirmed",
  },
];

export const mockRevenueData = [
  { month: "Feb", revenue: 18400, leads: 22 },
  { month: "Mar", revenue: 24100, leads: 31 },
  { month: "Apr", revenue: 21700, leads: 27 },
  { month: "May", revenue: 31200, leads: 38 },
  { month: "Jun", revenue: 28800, leads: 34 },
  { month: "Jul", revenue: 16400, leads: 19 },
];

export const mockPipelineData = [
  { stage: "New", count: 2, value: 12000 },
  { stage: "Contacted", count: 3, value: 15500 },
  { stage: "Appt Set", count: 2, value: 11300 },
  { stage: "Estimate", count: 2, value: 15600 },
  { stage: "Won", count: 2, value: 16400 },
];
